language: c++
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake
      - swig
      - python3-dev

install:
  - git clone https://github.com/swig/swig.git && cd swig && ./autogen.sh && ./configure --prefix=$HOME/.local --without-alllang && make -j2 && make install && cd ..

script:
  - mkdir build && cd build
  - cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
  - make install VERBOSE=1
  - python3 ../test-fieldfunction.py
  - rm -rf * $HOME/.local/lib/python*
  - cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX=$HOME/.local -DSWIG_EXECUTABLE=$HOME/.local/bin/swig  ..
  - make install VERBOSE=1
  - python3 ../test-fieldfunction.py
